### ISSUE TITLE
Besoin d'un avis

### ISSUE THREAD

**Issue by notabene** [notabene/Brouillons#1]
Salut @karlcow

Mon host mail (webmail.gnadi.net) est bloqué par ton host mail (gandi.net) qui considère aujourd'hui que le mien envoie du spam. Whatever.

Ta discussion de 2h du matin avec [H] m'a fait penser que ce serait bien de faire une synthèse à laquelle se référer, j'ai donc commencé à le faire là : https://github.com/notabene/Brouillons/blob/master/comment-inserer-du-svg-dans-une-page.txt

Dis-moi si je dis des bêtises :)

Et si ça te paraît bien j'en ferai un article mieux rédigé.

**Comment by karlcow** [comment]
Ah intéressant, il faudrait que tu me donnes le contenu du message avec ses headers sur un gist privé par exemple par IRC ;)

Une référence supplémentaire.

* https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image

**Comment by notabene** [comment]
Merci, je t'ai envoyé le message sur IRC. Closing now.
